#!/sbin/busybox sh

export BOOTREC_EVENT_NODE="/dev/input/event11 c 13 75"
export BOOTREC_EVENT_NODE2="/dev/input/event4 c 13 68"
export BOOTREC_EVENT="/dev/input/event11"
export BOOTREC_EVENT2="/dev/input/event4"
export BOOTREC_LED_RED="/sys/class/leds/led:rgb_red/brightness"
export BOOTREC_LED_GREEN="/sys/class/leds/led:rgb_green/brightness"
export BOOTREC_LED_BLUE="/sys/class/leds/led:rgb_blue/brightness"
export BOOTREC_VIBRATOR="/sys/class/timed_output/vibrator/enable"
export BOOTREC_FOTA_NODE="/dev/block/mmcblk0p27 b 179 27"
export BOOTREC_FOTA="/dev/block/mmcblk0p27"
